// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class BreadType {
  private BreadType() { }
  public static final byte White = 0;
  public static final byte MultiGrain = 1;

  public static final String[] names = { "White", "MultiGrain", };

  public static String name(int e) { return names[e]; }
}

