// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class ResponseCode {
  private ResponseCode() { }
  public static final byte OK = 0;
  public static final byte BAD_REQUEST = 1;

  public static final String[] names = { "OK", "BAD_REQUEST", };

  public static String name(int e) { return names[e]; }
}

