// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class DispenserStatus {
  private DispenserStatus() { }
  public static final byte OPTIMAL = 0;
  public static final byte PARTIAL = 1;
  public static final byte BLOCKAGE = 2;

  public static final String[] names = { "OPTIMAL", "PARTIAL", "BLOCKAGE", };

  public static String name(int e) { return names[e]; }
}

