// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class MeatType {
  private MeatType() { }
  public static final byte Beef = 0;
  public static final byte Pork = 1;
  public static final byte Chicken = 2;

  public static final String[] names = { "Beef", "Pork", "Chicken", };

  public static String name(int e) { return names[e]; }
}

