// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class Microwavetatus {
  private Microwavetatus() { }
  public static final byte GOOD = 0;
  public static final byte BAD = 1;

  public static final String[] names = { "GOOD", "BAD", };

  public static String name(int e) { return names[e]; }
}

