// automatically generated by the FlatBuffers compiler, do not modify

package com.networking.flatbuffers.zmq;

@SuppressWarnings("unused")
public final class MilkType {
  private MilkType() { }
  public static final byte FatFree = 0;
  public static final byte Whole = 1;

  public static final String[] names = { "FatFree", "Whole", };

  public static String name(int e) { return names[e]; }
}

